export const Skills = {
  acrobatics: String,
  ancientLore: String,
  armoury: String,
  climb: String,
  leadership: String,
  navigation: String,
  perception: String,
  pickLock: String,
  readRunes: String,
  stealth: String,
  strength: String,
  survival: String,
  swim: String,
  track: String,
  traps: String,
};
